### ISSUE TITLE
Error Occured while run command "paster setup-app test.ini2"

### ISSUE THREAD

**Issue by ArtiWavale** [LinOTP/LinOTP#133]
Hello,

Im using ubuntu 16.04 system and I am trying to install linotp 2.9.0.5 release version on my system but I am facing problem which is mention in below so I cound not understand how to solved this error . If anyone knows how to solve this problem so please guide me.

----------------------------------------------------------------------------

Traceback (most recent call last):

File "/opt/armorotp_dev_venv/bin/paster", line 11, in <module>

load_entry_point('PasteScript', 'console_scripts', 'paster')()

File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 104, in run

invoke(command, command_name, options, args[1:])

File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 143, in invoke

exit_code = runner.run(args)

File "/usr/lib/python2.7/dist-packages/paste/script/appinstall.py", line 68, in run

return super(AbstractInstallCommand, self).run(new_args)

File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 238, in run

result = self.command()

File "/usr/lib/python2.7/dist-packages/paste/script/appinstall.py", line 447, in command

conf = appconfig(config_spec, relative_to=os.getcwd())

File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 261, in appconfig

global_conf=global_conf)

File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext

global_conf=global_conf)

File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig

return loader.get_context(object_type, name, global_conf)

File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 454, in get_context

section)

File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use

object_type, name=use, global_conf=global_conf)

File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 406, in get_context

global_conf=global_conf)

File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext

global_conf=global_conf)

File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg

return loader.get_context(object_type, name, global_conf)

File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 620, in get_context

object_type, name=name)

File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 646, in find_egg_entry_point

possible.append((entry.load(), protocol, entry.name))

File "/opt/armorotp_dev_venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load

return self.resolve()

File "/opt/armorotp_dev_venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve

module = __import__(self.module_name, fromlist=['__name__'], level=0)

File "/opt/ArmorOTP/linotpd/src/linotp/config/middleware.py", line 34, in <module>

from pylons.middleware import ErrorHandler, StatusCodeRedirect

File "/opt/armorotp_dev_venv/lib/python2.7/site-packages/Pylons-1.0.3-py2.7.egg/pylons/middleware.py", line 7, in <module>

from weberror.evalexception import EvalException

File "/opt/armorotp_dev_venv/lib/python2.7/site-packages/WebError-0.13.1-py2.7.egg/weberror/evalexception.py", line 47, in <module>

from weberror import errormiddleware, formatter, collector

File "/opt/armorotp_dev_venv/lib/python2.7/site-packages/WebError-0.13.1-py2.7.egg/weberror/errormiddleware.py", line 14, in <module>

from weberror import formatter, collector, reporter

File "/opt/armorotp_dev_venv/lib/python2.7/site-packages/WebError-0.13.1-py2.7.egg/weberror/formatter.py", line 16, in <module>

from pygments.lexers import ClassNotFound, PythonLexer, TextLexer, \

File "/opt/armorotp_dev_venv/lib/python2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/lexers/__init__.py", line 330, in __getattr__

_load_lexers(info[0])

File "/opt/armorotp_dev_venv/lib/python2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/lexers/__init__.py", line 45, in _load_lexers

mod = __import__(module_name, None, None, ['__all__'])

File "/opt/armorotp_dev_venv/lib/python2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/lexers/python.py", line 14, in <module>

from pygments.lexer import Lexer, RegexLexer, include, bygroups, using, \

File "/opt/armorotp_dev_venv/lib/python2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/lexer.py", line 49

class Lexer(metaclass=LexerMeta):

^

SyntaxError: invalid syntax

-----------------------------------------------------------------------------

Thanks and Regards
Arti

**Comment by devel-linotp** [comment]
Hi there

We ran into this problem too. There has been a change to the Pygments
library from version 2.6. You can work around it by installing a 2.5.x
version instead. I checked in a commit to limit the version here:

https://github.com/LinOTP/LinOTP/commit/6e40f08c3d796bdd57d15a3ed5f38f18b7bc30cc

If you are using a virtual environment, the pip command to do this
should look something like this:

pip install "Pygments<2.6"

Regards
Chris

**Comment by ArtiWavale** [comment]
Thanks Chris, It is working now

1] Added ldap user with email attribute in LinOTP V2.9.0.5
2] created realm for that particular user
3] created email token for that particular user
4] click check box from system config option

---> Split at @ sign(SplitAtSign)
---> FailCounterIncOnFalsePin
---> PrependPin
--->Auto resync timeout: 240

5] Provider Config -->E-Mail Provider Config --> New
{ "SMTP_SERVER":"xxxxx", 
"SMTP_USER":"xxxxx", 
"SMTP_PASSWORD":"xxxxx", 
"EMAIL_FROM":"xxxxx", 
"EMAIL_SUBJECT":"Your OTP"}

6] Created Policy

--->Scope : Authentication, Action : otppin= 1, challenge_response=*, email_provider=emailp, 
--->Scope : enrollment, Action : autoenrollment=email, 

7] https://IP:5001/auth/index3
Username: xxxx@realm
OTP Pin: xxxxxxx
OTP Value :
8] still email OTP will not generated
9] If any one solution then please suggest me

**Comment by ArtiWavale** [comment]
If we are using firewall for system security purpose then E-mail OTP not generated....
because I tested LinOTP on those system which not have firewall setting and LinOTP working successfully on it but when I tried to test same source code of LinOTP on those system which have firewall security setting, LinOTP not working successfully means email OTP not generated on particular mail ID. 

so how can generate email OTP on secure system which connected to firewall?

**Comment by ArtiWavale** [comment]
I am working with Ubuntu 16.04.01, Ram 16 GB, Hard disks 1TB, VirutalBox 6.1

I have installed successfully LinOTP v2.9.0.5 release version on two different system with same step procedure but result will occurred like E-mail OTP is generated successfully on one system and  E-mail OTP not generated on another system. 

What is system configuration is required for LinOTP to generate E-mail OTP and why is it happening  like this.

**Comment by megfault** [comment]
The issue with paster has been solved, so I am closing this. The issue on the generation of OTP emails is discussed in #134.
