### ISSUE TITLE
Traceback Error Ocured while run "make develop" command in /opt/LinOTP folrder

### ISSUE THREAD

**Issue by ArtiWavale** [LinOTP/LinOTP#145]
I'm using Ubuntu 18.04.01 operating system and LinOTP version 2.10.7.2. If anyone know the solution. please help me
**Command : /opt/LinOTP/---->make develop**
--------------------------------------------------------------------------------------------------------------
Running MarkupSafe-2.0.0a1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-2ks0Yd/MarkupSafe-2.0.0a1/egg-dist-tmp-foxyY8
Traceback (most recent call last):
  File "setup.py", line 278, in <module>
    cmdclass={'build_py': Build}
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/command/develop.py", line 156, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-2ks0Yd/MarkupSafe-2.0.0a1/setup.py", line 56, in <module>
    def get_file_contents(file_path):
  File "/tmp/easy_install-2ks0Yd/MarkupSafe-2.0.0a1/setup.py", line 43, in run_setup
    
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
    dist.parse_config_files()
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/opt/linotp_dev_venv/local/lib/python2.7/site-packages/setuptools/config.py", line 350, in _parse_attr
    value = getattr(module, attr_name)
AttributeError: 'module' object has no attribute '__version__'
Makefile:136: recipe for target 'develop' failed
make: *** [develop] Error 1
------------------------------------------------------------
Thanks and Regards
Arti

**Comment by reinies** [comment]
Hey Arti,

I tried the same and it worked. Can you provide more details what you did precisely.
(In version 2.10.7.2 we also have a _Develop.md_ which describe what to install, how to setup a python virtual env ...)

After setting up the python virtual env and the Debian/Ubuntu dependencies try:
`git clone https://github.com/linotp/linotp`
`cd linotp`
`git checkout releases/2.10.7.2`
`cd linotpd/src`
`python setup.py develop`

Cheers
Reinhard

**Comment by lukengda** [comment]
We are closing this issue for now, as no additional problems are reported
