### ISSUE TITLE
Email OTP autoenrollment

### ISSUE THREAD

**Issue by behzad-kh** [LinOTP/LinOTP#152]
Hi
I have configured the autoenrollment over the linotp.org documentation.

Following is the error output when using the https://LINOTPSERVER/auth/index url with the correct username/password:

tail -f /var/log/linotp/linotp.log

2020/10/27 - 12:19:08 ERROR [linotp.lib.token][auto_enrollToken #316] Failed to autoenroll notify user!
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linotp/lib/token.py", line 310, in auto_enrollToken
    notified = notify_user(user, 'autoenrollment', info, required=True)
  File "/usr/lib/python2.7/dist-packages/linotp/provider/notification.py", line 83, in notify_user
    'No notification has been sent - %r provider defined?' % action)
NotificationException: No notification has been sent - 'autoenrollment' provider defined?
2020/10/27 - 12:19:08 ERROR [linotp.tokens.emailtoken][_sendEmail #490] Failed to submit EMail: TypeError('character ma
pping must return integer, None or unicode',)
2020/10/27 - 12:19:08 ERROR [linotp.lib.challenges][create_challenge #219] Failed to create challenge: TypeError('chara
cter mapping must return integer, None or unicode',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linotp/lib/challenges.py", line 205, in create_challenge
    token.createChallenge(transactionid, options=options)
  File "/usr/lib/python2.7/dist-packages/linotp/tokens/emailtoken.py", line 355, in createChallenge
    success, status_message = self._sendEmail()
  File "/usr/lib/python2.7/dist-packages/linotp/tokens/emailtoken.py", line 487, in _sendEmail
   replacements=replacements)
  File "/usr/lib/python2.7/dist-packages/linotp/provider/emailprovider/__init__.py", line 526, in submitMessage
    smtp_connection.login(self.smtp_user, self.smtp_password)
  File "/usr/lib/python2.7/smtplib.py", line 608, in login
    (code, resp) = self.docmd(encode_cram_md5(resp, user, password))
  File "/usr/lib/python2.7/smtplib.py", line 572, in encode_cram_md5
    response = user + " " + hmac.HMAC(password, challenge).hexdigest()
  File "/usr/lib/python2.7/hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode
2020/10/27 - 12:19:08 ERROR [linotp.lib.challenges][create_challenge #244] Failed to create or init challenge. Reason was "TypeError('character mapping must return integer, None or unicode',)"
2020/10/27 - 12:19:08 ERROR [linotp.lib.token][auto_enrollToken #336] Failed to create challenge!
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linotp/lib/token.py", line 328, in auto_enrollToken
    options=options)
  File "/usr/lib/python2.7/dist-packages/linotp/lib/challenges.py", line 245, in create_challenge
    raise ReasonException
TypeError: character mapping must return integer, None or unicode
2020/10/27 - 12:19:08 ERROR [linotp.controllers.validate][check #260] [check] validate/check failed: TypeError('character mapping must return integer, None or unicode',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linotp/controllers/validate.py", line 231, in check
    (ok, opt) = self._check(param)
  File "/usr/lib/python2.7/dist-packages/linotp/controllers/validate.py", line 161, in _check
    (ok, opt) = vh.checkUserPass(user, passw, options=options)
  File "/usr/lib/python2.7/dist-packages/linotp/lib/auth/validate.py", line 573, in checkUserPass
     options=options)
  File "/usr/lib/python2.7/dist-packages/linotp/lib/token.py", line 343, in auto_enrollToken
    raise exx
TypeError: character mapping must return integer, None or unicode

**Comment by megfault** [comment]
Hi! Which version of LinOTP you are running?

**Comment by marliyev** [comment]
Hi, same issue here: 

TypeError('character mapping must return integer, None or unicode'

LinOTP 2.12.1

**Comment by xt-kay** [comment]
Hi, 
sorry for the problem. When looking at the log file the importent message to me is
`NotificationException: No notification has been sent - 'autoenrollment' provider defined?`

So it seems a problem with your settings, which might not be complete.
Are you using the notification and autoenrollment setup?

To analyse the problem, could you please provide the used policy settings and your provider setup (wo passwords).

Best regards,
   Kay

**Comment by marliyev** [comment]
Hi, on my config all policy in place, am not receiving any error except this: TypeError('character mapping must return integer, None or unicode'
