### ISSUE TITLE
Healthcheck URL /manage/maintainence/ok reports errors

### ISSUE THREAD

**Issue by direvus** [LinOTP/LinOTP#156]
Hello,

I am finding that my linotp log file is completely spammed with error messages resulting from regular health checks of the server.

Every few seconds, the load balancer makes a request to /manage/maintainence/ok to check the health of the server.  The response status is HTTP 200 OK, but the response body shows this:

```
{
   "version": "LinOTP 2.11.1",
   "jsonrpc": "2.0802",
   "result": {
      "status": false,
      "error": {
         "message": "You have no valid session!",
         "code": -311
      }
   },
   "id": 1
}
```

My linotp log file is recording this message every time such a request occurs:

```
2021/02/14 - 16:08:26 ERROR [linotp.lib.util][check_session #211] The request did not pass a valid session!
2021/02/14 - 16:08:26 ERROR [linotp.controllers.manage][__before__ #134] [__before__::u'maintainence'] exception <HTTPUnauthorized at 0x7f86d46ec780 401 Unauthorized>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/linotp/controllers/manage.py", line 131, in __before__
    check_session(request)
  File "/usr/lib/python2.7/site-packages/linotp/lib/util.py", line 212, in check_session
    abort(401, "You have no valid session!")
  File "/usr/lib/python2.7/site-packages/pylons/controllers/util.py", line 215, in abort
    raise exc
HTTPUnauthorized: You have no valid session!
```

I get the same result from the server whether I hit the URL with a curl command (no auth, no session) or from my browser with a successfully authenticated session.

There are a few things about this that I find confusing.

- Why would the controller be expecting a "valid session" for a health check URL?  The whole point of a health check is that it can be requested without a session, no?
- If the controller is throwing a HTTPUnauthorized exception, why is the HTTP status still 200 OK?
- Why do I get a "no valid session" response even when I do, in fact, have a valid session?

Thanks in advance for any insight.

**Comment by direvus** [comment]
Hi Kay, thanks for answering my questions.

If `/validate/ok` is the appropriate endpoint to use for a basic server status, I think that resolves my issue.
