### ISSUE TITLE
Failed to upgrade database from 2.12.1 to 3.0

### ISSUE THREAD

**Issue by khrustalev-rg** [LinOTP/LinOTP#168]
I have installed linotp-server v.2.12.1 and I'm going to update it to 3.0. When I'm trying to do this, database upgrade process finish with fail.

`root@a72a49827ee7:/opt/linotp# linotp init database
Configuration loaded from /opt/linotp/files/linotp.cfg
2021-10-08 17:11:09,616 ERROR: Failed to upgrade database! AttributeError("'LegacyCursorResult' object has no attribute 'next'",) [in /opt/linotp/LinOTP/linotpd/src/linotp/model/migrate.py:477]
Traceback (most recent call last):
  File "/opt/linotp/LinOTP/linotpd/src/linotp/model/migrate.py", line 474, in migrate
    _success = migration_step()
  File "/opt/linotp/LinOTP/linotpd/src/linotp/model/migrate.py", line 630, in migrate_3_0_0_0
    migrated_tables = mysql_mig.migrate_schema()
  File "/opt/linotp/LinOTP/linotpd/src/linotp/model/migrate.py", line 256, in migrate_schema
    schema_def =  self._query_schema(table)
  File "/opt/linotp/LinOTP/linotpd/src/linotp/model/migrate.py", line 226, in _query_schema
    return results.next()[1]
AttributeError: 'LegacyCursorResult' object has no attribute 'next'
Exception occured during database setup: AttributeError("'LegacyCursorResult' object has no attribute 'next'",)
Failed to create database: 'LegacyCursorResult' object has no attribute 'next'`

How can I fix this error?

**Comment by lukengda** [comment]
This problem should be fixed by now. If you still encounter this problem on master than please let us know.

**Comment by duczz** [comment]
@khrustalev-rg can you tell me please your upgrade steps. I need to Upgrade too :)
