### ISSUE TITLE
Old version of LinOTP on PyPI

### ISSUE THREAD

**Issue by spacefreak86** [LinOTP/LinOTP#175]
Dear LinOTP developers

According to the readme, LinOTP should be installed with pip, but the latest release of LinOTP on PyPI is very old:
- LinOTP 2.11.1

Do you have a schedule, when the current release will be pushed to PyPI? Or do I have to build it from source to get the newest version?

Thanks in advance for your help.

**Comment by tometzky** [comment]
I was able to work-around this and install version 3.1 by using:
```
pip3 install "git+https://github.com/LinOTP/LinOTP.git@release/3.1"
```
For version 3.0 it was:
```
pip3 install "git+https://github.com/LinOTP/LinOTP.git@release/3.0#subdirectory=linotpd/src/"
```

But be aware, that if you automate this, and run it too often, then GitHub will ban you temporarily.

Versions 2.*, up to 2.12.14, released 2022-02-16, do not support Python3 - when you try to install it on a reasonably recent distribution you'll get this error:
```
Collecting PasteScript<=1.7.5
  Downloading PasteScript-1.7.5.tar.gz (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.7/129.7 KB 8.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mbl23pxd/pastescript_24f97e22bf7f4b4f969c46262fe81fe3/setup.py", line 16
          print 'Warning: no news for this version found'
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Warning: no news for this version found')?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

This is caused by a strange requirement of `PasteScript<=1.7.5` in `linotpd/src/setup.py` - a version which was released in 2011. There's already PasteScript 3.* available, with Python3 support, so maybe it is easy to fix by just changing the requirement.
