### ISSUE TITLE
Python error "ImportError: cannot import name 'verify_jwt_in_request_optional' from 'flask_jwt_extended'" 

### ISSUE THREAD

**Issue by corrugatedcardboard** [LinOTP/LinOTP#215]
OS: Ubuntu 22.04.2 LTS minimal. 

Hi Guys,

I tried installing and setting up LinOTP according to this documentation entry:
https://www.linotp.org/doc/latest/part-installation/server-installation/deb_install.html

The apt-get command seems to find the correct files and the newest version, however the following error message quickly appears:

```shell
LinOTP: Using existing log directory: /var/log/linotp
LinOTP: Using existing lib directory: /var/lib/linotp
LinOTP: Using existing cache directory: /var/cache/linotp
LinOTP: Using existing etc directory: /etc/linotp
LinOTP: Using existing template directory: /etc/linotp/custom-templates
dbconfig-common: writing config to /etc/dbconfig-common/linotp.conf
linotp already exists and has privileges on linotp.
creating database linotp: already exists.
populating database via scriptfile...  LinOTP: SQL configuration in /etc/linotp/conf.d/01-debian-database.cfg created.
LinOTP: Initialising database
Traceback (most recent call last):
  File "/usr/bin/linotp", line 11, in <module>
    load_entry_point('LinOTP==3.2.3', 'console_scripts', 'linotp')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/linotp/cli/__init__.py", line 41, in <module>
    from linotp.app import create_app
  File "/usr/lib/python3/dist-packages/linotp/app.py", line 38, in <module>
    from flask_jwt_extended import (
ImportError: cannot import name 'verify_jwt_in_request_optional' from 'flask_jwt_extended' (/usr/lib/python3/dist-packages/flask_jwt_extended/__init__.py)
error encountered populating database:
/usr/share/dbconfig-common/scripts/linotp/install/mysql exited with non-zero status\nIf the script logged anything about what went wrong,\n it can be found in /var/log/apt/term.log.``` `

///
I tried googling and installing the newest flask version with pip, however this didn't solve the issue.
Am I doing something wrong during the installation?

Thanks in advance!

**Comment by corrugatedcardboard** [comment]
Just tested with Ubuntu 22.04.2 LTS, the regular, not the minimized version. The issue is still apparent.

**Comment by lukengda** [comment]
Hi @corrugatedcardboard, thanks for your further research. You have correctly identified that we are currently not compatible with the new major version of flask-jwt-extended. We are planning to include this in a future release.
