### ISSUE TITLE
`paster setup-app ./etc/linotp2/linotp.ini` verses MySQL 5.6 results in ` (OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes')`

### ISSUE THREAD

**Issue by stefanlasiewski** [LinOTP/LinOTP#29]
I am installing LinOTP on a new EL6.7 server running MySQL 5.6, installed with default settings, and using InnoDB which is the default engine.

I ran into problems when using your script to create database tables for the Token Database.

The instructions at http://linotp.org/doc/latest/part-installation/server-installation/pip_install.html#setup-token-database say the following:

Now you can create the database tables:
paster setup-app /etc/linotp2/linotp.ini

However, when I try this, MySQL complains with a scary error:

```
(LINOTP)[root@myhost LINOTP]# paster setup-app ./etc/linotp2/linotp.ini
Running setup_app() from linotp.websetup
Traceback (most recent call last):
  File "/opt/LINOTP/bin/paster", line 9, in <module>
...
sqlalchemy.exc.OperationalError: (OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes') 'CREATE INDEX `ix_Token_LinOtpUserid` ON `Token` (`LinOtpUserid`)' ()
```

That error is rather subtle, but I believe it means that the key will be very different than expected.

Subsequent runs of the paster command run without complaints:

```
(LINOTP)[root@myhost LINOTP]# paster setup-app ./etc/linotp2/linotp.ini
Running setup_app() from linotp.websetup
(LINOTP)[root@sphinxdev LINOTP]# 
```

I'll include the longer stack trace below.

**Comment by stefanlasiewski** [comment]
Longer traceback:

```
(LINOTP)[root@myhost LINOTP]# paster setup-app ./etc/linotp2/linotp.ini
Running setup_app() from linotp.websetup
Traceback (most recent call last):
  File "/opt/LINOTP/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
  File "/opt/LINOTP/lib/python2.6/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/opt/LINOTP/lib/python2.6/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/opt/LINOTP/lib/python2.6/site-packages/paste/script/appinstall.py", line 66, in run
    return super(AbstractInstallCommand, self).run(new_args)
  File "/opt/LINOTP/lib/python2.6/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/opt/LINOTP/lib/python2.6/site-packages/paste/script/appinstall.py", line 453, in command
    self, config_file, section, self.sysconfig_install_vars(installer))
  File "/opt/LINOTP/lib/python2.6/site-packages/paste/script/appinstall.py", line 595, in setup_config
    mod.setup_app, command, filename, section, vars)
  File "/opt/LINOTP/lib/python2.6/site-packages/paste/script/appinstall.py", line 611, in _call_setup_app
    func(command, conf, vars)
  File "/opt/LINOTP/lib/python2.6/site-packages/linotp/websetup.py", line 76, in setup_app
    linotp.lib.base.setup_app(conf.local_conf, conf.global_conf, unitTest)
  File "/opt/LINOTP/lib/python2.6/site-packages/linotp/lib/base.py", line 209, in setup_app
    meta.metadata.create_all(bind=meta.engine)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/sql/schema.py", line 3431, in create_all
    tables=tables)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1726, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1357, in _run_visitor
    **kwargs).traverse_single(element)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/sql/visitors.py", line 120, in traverse_single
    return meth(obj, **kw)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/sql/ddl.py", line 713, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/sql/visitors.py", line 120, in traverse_single
    return meth(obj, **kw)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/sql/ddl.py", line 736, in visit_table
    self.traverse_single(index)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/sql/visitors.py", line 120, in traverse_single
    return meth(obj, **kw)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/sql/ddl.py", line 748, in visit_index
    self.connection.execute(CreateIndex(index))
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 895, in _execute_ddl
    compiled
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/opt/LINOTP/lib/python2.6/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/LINOTP/lib/python2.6/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/LINOTP/lib/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
sqlalchemy.exc.OperationalError: (OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes') 'CREATE INDEX `ix_Token_LinOtpUserid` ON `Token` (`LinOtpUserid`)' ()
(LINOTP)[root@myhost LINOTP]#
```

**Comment by stefanlasiewski** [comment]
A workaround seems to be to modify some MySQL InnoDB settings:

```
innodb_large_prefix=true
innodb_file_format=barracuda
```

From https://dba.stackexchange.com/questions/49913/specified-key-was-too-long-max-key-length-is-1000-bytes-in-mysql-5-6

However, this doesn't work for me yet.

**Comment by keyidentity-mirko** [comment]
Hi Stefan,

sorry for the late reply. This seems to be a problem with the innodb_file_format. We experience no problem with the Index or Column size with he following inodb format in use:

mysql> SHOW VARIABLES LIKE 'innodb_file_format';
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| innodb_file_format | Antelope |
+--------------------+----------+
1 row in set (0.00 sec)

Best regards,

Mirko
