### ISSUE TITLE
problem with upgrading LinOTP 2.8.1 >> 2.9

### ISSUE THREAD

**Issue by AkagiS** [LinOTP/LinOTP#39]
pip2.7 install --upgrade linotp
Collecting linotp
Requirement already up-to-date: simplejson>=2.0 in ./lib/python2.7/site-packages (from linotp)
Requirement already up-to-date: configobj>=4.6.0 in ./lib/python2.7/site-packages (from linotp)
Collecting LinOtpUserIdResolver>=2.7 (from linotp)
Collecting pycryptodomex>=3.4 (from linotp)
Requirement already up-to-date: httplib2 in ./lib/python2.7/site-packages (from linotp)
Requirement already up-to-date: docutils>=0.4 in ./lib/python2.7/site-packages (from linotp)
Requirement already up-to-date: qrcode>=2.4 in ./lib/python2.7/site-packages (from linotp)
Requirement already up-to-date: Pylons>=0.9.7 in ./lib/python2.7/site-packages (from linotp)
Collecting SQLAlchemy>=0.6 (from linotp)
Requirement already up-to-date: repoze.who<=1.1 in ./lib/python2.7/site-packages (from linotp)
Requirement already up-to-date: pyrad>=1.1 in ./lib/python2.7/site-packages (from linotp)
Collecting WebOb (from linotp)
  Using cached WebOb-1.6.1-py2.py3-none-any.whl
Requirement already up-to-date: netaddr in ./lib/python2.7/site-packages (from linotp)
Collecting pysodium>=0.6.8 (from linotp)
Requirement already up-to-date: six in ./lib/python2.7/site-packages (from configobj>=4.6.0->linotp)
Collecting python-ldap (from LinOtpUserIdResolver>=2.7->linotp)
Requirement already up-to-date: nose>=1.1.2 in ./lib/python2.7/site-packages (from Pylons>=0.9.7->linotp)
Requirement already up-to-date: MarkupSafe>=0.15 in ./lib/python2.7/site-packages (from Pylons>=0.9.7->linotp)
Requirement already up-to-date: PasteScript>=1.7.4.2 in ./lib/python2.7/site-packages (from Pylons>=0.9.7->linotp)
Requirement already up-to-date: WebHelpers>=0.6.4 in ./lib/python2.7/site-packages (from Pylons>=0.9.7->linotp)
Requirement already up-to-date: Routes>=1.12.3 in ./lib/python2.7/site-packages (from Pylons>=0.9.7->linotp)
Requirement already up-to-date: WebError>=0.10.3 in ./lib/python2.7/site-packages (from Pylons>=0.9.7->linotp)
Collecting WebTest>=1.3.1 (from Pylons>=0.9.7->linotp)
  Downloading WebTest-2.0.23-py2.py3-none-any.whl
Requirement already up-to-date: Tempita>=0.5.1 in ./lib/python2.7/site-packages (from Pylons>=0.9.7->linotp)
Requirement already up-to-date: Paste>=1.7.5.1 in ./lib/python2.7/site-packages (from Pylons>=0.9.7->linotp)
Requirement already up-to-date: PasteDeploy>=1.5.0 in ./lib/python2.7/site-packages (from Pylons>=0.9.7->linotp)
Requirement already up-to-date: Mako>=0.5.0 in ./lib/python2.7/site-packages (from Pylons>=0.9.7->linotp)
Collecting decorator>=3.3.2 (from Pylons>=0.9.7->linotp)
  Downloading decorator-4.0.10-py2.py3-none-any.whl
Collecting FormEncode>=1.2.4 (from Pylons>=0.9.7->linotp)
Requirement already up-to-date: Beaker>=1.5.4 in ./lib/python2.7/site-packages (from Pylons>=0.9.7->linotp)
Collecting setuptools (from repoze.who<=1.1->linotp)
  Downloading setuptools-26.0.0-py2.py3-none-any.whl (459kB)
    100% |████████████████████████████████| 460kB 448kB/s
Collecting zope.interface (from repoze.who<=1.1->linotp)
Requirement already up-to-date: repoze.lru>=0.3 in ./lib/python2.7/site-packages (from Routes>=1.12.3->Pylons>=0.9.7->linotp)
Requirement already up-to-date: Pygments in ./lib/python2.7/site-packages (from WebError>=0.10.3->Pylons>=0.9.7->linotp)
Requirement already up-to-date: waitress>=0.8.5 in ./lib/python2.7/site-packages (from WebTest>=1.3.1->Pylons>=0.9.7->linotp)
Collecting beautifulsoup4 (from WebTest>=1.3.1->Pylons>=0.9.7->linotp)
  Downloading beautifulsoup4-4.5.1-py2-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 761kB/s
Requirement already up-to-date: funcsigs in ./lib/python2.7/site-packages (from Beaker>=1.5.4->Pylons>=0.9.7->linotp)
Installing collected packages: setuptools, python-ldap, LinOtpUserIdResolver, pycryptodomex, SQLAlchemy, WebOb, pysodium, linotp, beautifulsoup4, WebTest, decorator, FormEncode, zope.interface
  **Found existing installation: setuptools 1.4.2
    Uninstalling setuptools-1.4.2:
      Successfully uninstalled setuptools-1.4.2**
  Found existing installation: python-ldap 2.4.25
    Uninstalling python-ldap-2.4.25:
      Successfully uninstalled python-ldap-2.4.25
  Found existing installation: LinOtpUserIdResolver 2.8.1
    Uninstalling LinOtpUserIdResolver-2.8.1:
      Successfully uninstalled LinOtpUserIdResolver-2.8.1
  Found existing installation: SQLAlchemy 1.0.13
    Uninstalling SQLAlchemy-1.0.13:
      Successfully uninstalled SQLAlchemy-1.0.13
  Found existing installation: WebOb 1.3.1
    Uninstalling WebOb-1.3.1:
      Successfully uninstalled WebOb-1.3.1
  Found existing installation: LinOTP 2.8.1
    Uninstalling LinOTP-2.8.1:
      Successfully uninstalled LinOTP-2.8.1
  Found existing installation: beautifulsoup4 4.4.1
    Uninstalling beautifulsoup4-4.4.1:
      Successfully uninstalled beautifulsoup4-4.4.1
  Found existing installation: WebTest 2.0.21
    Uninstalling WebTest-2.0.21:
      Successfully uninstalled WebTest-2.0.21
  Found existing installation: decorator 4.0.9
    Uninstalling decorator-4.0.9:
      Successfully uninstalled decorator-4.0.9
  Found existing installation: FormEncode 1.3.0
    Uninstalling FormEncode-1.3.0:
      Successfully uninstalled FormEncode-1.3.0
  Found existing installation: zope.interface 4.1.3
    Uninstalling zope.interface-4.1.3:
      Successfully uninstalled zope.interface-4.1.3
Successfully installed FormEncode LinOtpUserIdResolver SQLAlchemy WebOb WebTest beautifulsoup4 decorator linotp pycryptodomex pysodium python-ldap setuptools zope.interface
Traceback (most recent call last):
  File "/opt/LINOTP/bin/pip2.7", line 11, in <module>
    sys.exit(main())
  File "/opt/LINOTP/lib/python2.7/site-packages/pip/__init__.py", line 221, in main
    return command.main(cmd_args)
  File "/opt/LINOTP/lib/python2.7/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/opt/LINOTP/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/opt/LINOTP/lib/python2.7/site-packages/pip/utils/__init__.py", line 848, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/opt/LINOTP/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 619, in __init__
    self.add_entry(entry)
  File "/opt/LINOTP/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 675, in add_entry
    for dist in find_distributions(entry, True):
  File "/opt/LINOTP/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1942, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/opt/LINOTP/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/opt/LINOTP/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1824, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/opt/LINOTP/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1704, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/opt/LINOTP/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1644, in load
    mtime = os.stat(path).st_mtime
**OSError: [Errno 2] No such file or directory: '/opt/LINOTP/lib/python2.7/site-packages/setuptools-1.4.2-py2.7.egg'**

**Comment by AkagiS** [comment]
fixed

pip2.7 uninstall  setuptools
pip2.7 install  setuptools
