### ISSUE TITLE
libsodium httpd error after upgrading from LinOTP 2.8.0.1 to 2.9 using pip

### ISSUE THREAD

**Issue by wennit** [LinOTP/LinOTP#42]
Hi,

We currently run LinOTP 2.8.0.1 and are trying to upgrade to 2.9 - hopefully to fix some email problems we have been experiencing with issuing temporary email tokens.

The OS we have it installed on is CentOS 6.8 with Python 2.6 (I have seen the warnings about upgrading Python during the Pip update but hasn't failed the update)

The site was setup using the virtualenv + pip method and I am now using the update instructions from https://www.linotp.org/doc/latest/part-installation/updates/index.html#updates (which are out of date but potentially still valid).

After getting the environment setup, I ran `pip install --upgrade LinOTP LinOtpUserIdResolver SMSProvider`

When I visit the newly updated linotp site you see an Internal Server error and the httpd logs show the below. I have also tried using `linotp-pip-update` script as well as the above. We have this on VMware so I've been able to revert to the snapshot and try again.

> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx] mod_wsgi (pid=30751): Target WSGI script '/opt/LINOTP/etc/linotp2/linotpapp.wsgi' cannot be loaded as Python module.
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx] mod_wsgi (pid=30751): Exception occurred processing WSGI script '/opt/LINOTP/etc/linotp2/linotpapp.wsgi'.
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx] Traceback (most recent call last):
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/etc/linotp2/linotpapp.wsgi", line 14, in <module>
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     application = loadapp('config:%s' % INIFILE)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     return loadobj(APP, uri, name=name, **kw)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     global_conf=global_conf)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     global_conf=global_conf)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     return loader.get_context(object_type, name, global_conf)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 454, in get_context
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     section)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     object_type, name=use, global_conf=global_conf)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 406, in get_context
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     global_conf=global_conf)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     global_conf=global_conf)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     return loader.get_context(object_type, name, global_conf)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 620, in get_context
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     object_type, name=name)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 646, in find_egg_entry_point
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     possible.append((entry.load(), protocol, entry.name))
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2272, in load
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     return self.resolve()
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2278, in resolve
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/linotp/config/middleware.py", line 37, in <module>
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     from linotp.config.environment import load_environment
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/linotp/config/environment.py", line 37, in <module>
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     import linotp.lib.app_globals as app_globals
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/linotp/lib/app_globals.py", line 32, in <module>
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     from linotp.lib.security.provider import SecurityProvider
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/linotp/lib/security/provider.py", line 35, in <module>
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     from linotp.lib.crypt import zerome
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/linotp/lib/crypt.py", line 41, in <module>
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     from pysodium import crypto_scalarmult_curve25519 as calc_dh
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/opt/LINOTP/lib/python2.6/site-packages/pysodium/__init__.py", line 66, in <module>
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     sodium.crypto_pwhash_scryptsalsa208sha256_strprefix.restype = ctypes.c_char_p
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/usr/lib64/python2.6/ctypes/__init__.py", line 366, in __getattr__
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     func = self.__getitem__(name)
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]   File "/usr/lib64/python2.6/ctypes/__init__.py", line 371, in __getitem__
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx]     func = self._FuncPtr((name_or_ordinal, self))
> [Mon Oct 17 15:30:37 2016] [error] [client xxx.xxx.xxx.xxx] AttributeError: /usr/lib64/libsodium.so.4: undefined symbol: crypto_pwhash_scryptsalsa208sha256_strprefix

**Comment by lse-kay** [comment]
sorry for this - 
this isue is realted to the need of the native C lib libsodium - which is not directly provided on CentOS 6.8 :-(

**Comment by lse-kay** [comment]
ok - other option - have a look at 

https://github.com/LinOTP/LinOTP/issues/39

**Comment by tsmgeek** [comment]
That does not relate to my issue it seems.
Seems ile need to upgrade the OS to later version.
Does Centos7 libsodium contain what is needed?
