### ISSUE TITLE
OpenID server internal error

### ISSUE THREAD

**Issue by tsmgeek** [LinOTP/LinOTP#47]
Getting the following issue trying to access OpenID but cant 

`[Wed Jan 11 11:59:23 2017] [error] [client 85.240.213.171] Error - <type 'exceptions.AttributeError'>: can't set attribute
`

Debug mode
`[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171] mod_wsgi (pid=17640): Exception occurred processing WSGI script '/opt/LINOTP/etc/linotp2/linotpapp.wsgi'.
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171] Traceback (most recent call last):
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]   File "/opt/LINOTP/lib/python2.6/site-packages/repoze/who/middleware.py", line 107, in __call__
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]     app_iter = app(environ, wrapper.wrap_start_response)
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/cascade.py", line 130, in __call__
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]     return self.apps[-1](environ, start_response)
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]   File "/opt/LINOTP/lib/python2.6/site-packages/paste/registry.py", line 379, in __call__
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]     app_iter = self.application(environ, start_response)
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]   File "/opt/LINOTP/lib/python2.6/site-packages/pylons/middleware.py", line 155, in __call__
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]     self.app, environ, catch_exc_info=True)
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]   File "/opt/LINOTP/lib/python2.6/site-packages/pylons/util.py", line 50, in call_wsgi_application
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]     app_iter = application(environ, start_response)
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]   File "/opt/LINOTP/lib/python2.6/site-packages/weberror/evalexception.py", line 251, in __call__
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171]     "The EvalException middleware is not usable in a "
[Wed Jan 11 12:01:53 2017] [error] [client 85.240.213.171] AssertionError: The EvalException middleware is not usable in a multi-process environment
`

**Comment by keyidentity-mirko** [comment]
Hi,

this looks like an error occurring quite soon like after starting LinOTP. Which web server is LinOTP running at? Do you have any logs from the server? If LinOTP is starting up correctly - what are the exact steps to reproduce the observed behavior and could you please provide any debug logs?

Thank you and Best Regards,

Mirko
