### ISSUE TITLE
HTTP SMS issue

### ISSUE THREAD

**Issue by jfarcher** [LinOTP/LinOTP#59]
Having a strange issue I have setup our SMS messaging service as a provider, 
{ "URL":"https://enterprisemessaging.ee.co.uk/cgphttp/servlet/sendmsg", "PARAMETER": {"username":"XXXXXXXXXXXXXXXXXXXXX", "password": "XXXXXXXXXX"}, "SMS_TEXT_KEY":"text", "SMS_PHONENUMBER_KEY":"destination",
"RETURN_SUCCESS": "0 001 OK"}

It does send the message but the RETURN_SUCCESS is not matched, I've also tried REGEX.

Upon turning on the debug I see that an error page is returned
<html>
<body>
An error occurred.
</body>

</html>

I do recieve the text message.

Originally I presumed that it was our messaging service, but taking the URL from the debug log which is used and using curl from the command line I get a successful send and proper response.

I've tried adding <html> to the RETURN_SUCCESS string but even stranger things happen. for some reason a text message isn't sent, but the response match is successful.

Any ideas?

**Comment by jfarcher** [comment]
I've removed the RETURN_SUCCESS statement but SMS are definitely not sending now.
here is the DEBUG output.

2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][getPolicy #348] getting policies {} for params {'action': 'sms_provider', 'scope': 'authentication', 'realm': u'www.example.com'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][getPolicy #348] getting policies {} for params {'action': 'sms_provider', 'scope': 'authentication', 'realm': u'www.example.com'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][get_client_policy #2512] [get_client_policy] got policies {}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][get_client_policy #2512] [get_client_policy] got policies {}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][get_client_policy #2548] [get_client_policy] looking for policy without any client
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][get_client_policy #2548] [get_client_policy] looking for policy without any client
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.tokens.smstoken][sendSMS #886] [sendSMS] submitMessage: u'036104', to phone u'XXXXXXXXXXX'
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.tokens.smstoken][sendSMS #886] [sendSMS] submitMessage: u'036104', to phone u'XXXXXXXXXXX'
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][_submitMessage #76] [submitMessage] submitting message 036104 to XXXXXXXXXXX
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][_submitMessage #82] [submitMessage] by method GET
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][getParameters #188] [getParameters] urldata: {u'destination': u'XXXXXXXXXXX'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][getParameters #193] [getParameters] urldata: {u'text': u'036104', u'destination': u'XXXXXXXXXXX'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][getParameters #198] [getParameters] urldata: {u'username': u'http.bwd2fa@blackburn.gov.uk', u'text': u'036104', u'password': u'XXXXXXXX', u'destination': u'XXXXXXXXXXX'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][_submitMessage #85] [submitMessage] Now doing the Request
2017/05/10 - 14:14:54 INFO  {140507790042880} [urllib3.connectionpool][_new_conn #807] Starting new HTTPS connection (1): enterprisemessaging.ee.co.uk
2017/05/10 - 14:14:54 DEBUG {140507790042880} [urllib3.connectionpool][_make_request #401] "GET /cgphttp/servlet/sendmsg?username=XXXXXXXXXXXXXX&text=036104&destination=XXXXXXXXXXX&password=XXXXXXXX HTTP/1.1" 401 None
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][requests_request #317] HttpSMSProvider >><html>
<body>
An....
</body>

</html>
<<
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][_check_success #213] [_check_success] entering with config {u'URL': u'https://enterprisemessaging.ee.co.uk/cgphttp/servlet/sendmsg', u'SMS_PHONENUMBER_KEY': u'destination', u'SMS_TEXT_KEY': u'text', u'PARAMETER': {u'username': u'http.bwd2fa@blackburn.gov.uk', u'password': u'XXXXXXXX'}, 'timeout': u'120'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][_check_success #214] [_check_success] entering with reply <html>
<body>
An error occurred.
</body>

</html>

2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.tokens.smstoken][sendSMS #891] [sendSMS] message submitted
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.tokens.smstoken][sendSMS #891] [sendSMS] message submitted

**Comment by jfarcher** [comment]
I've removed the RETURN_SUCCESS option, but am defintely not recieving text messages now. Below is the DEBUG output (with obvious username/password URL changes)
I'm seeing a TCP stream occuring via tcpdump from the server to the expected endpoint.

2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][getPolicy #348] getting policies {} for params {'action': 'sms_provider', 'scope': 'authentication', 'realm': u'www.example.com'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][getPolicy #348] getting policies {} for params {'action': 'sms_provider', 'scope': 'authentication', 'realm': u'www.example.com'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][get_client_policy #2512] [get_client_policy] got policies {}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][get_client_policy #2512] [get_client_policy] got policies {}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][get_client_policy #2548] [get_client_policy] looking for policy without any client
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.policy][get_client_policy #2548] [get_client_policy] looking for policy without any client
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.tokens.smstoken][sendSMS #886] [sendSMS] submitMessage: u'036104', to phone u'XXXXXXXXXXX'
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.tokens.smstoken][sendSMS #886] [sendSMS] submitMessage: u'036104', to phone u'XXXXXXXXXXX'
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][_submitMessage #76] [submitMessage] submitting message 036104 to XXXXXXXXXXX
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][_submitMessage #82] [submitMessage] by method GET
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][getParameters #188] [getParameters] urldata: {u'destination': u'XXXXXXXXXXX'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][getParameters #193] [getParameters] urldata: {u'text': u'036104', u'destination': u'XXXXXXXXXXX'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][getParameters #198] [getParameters] urldata: {u'username': u'XXXXXXXXXX', u'text': u'036104', u'password': u'XXXXXXXX', u'destination': u'XXXXXXXXXXX'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][_submitMessage #85] [submitMessage] Now doing the Request
2017/05/10 - 14:14:54 INFO  {140507790042880} [urllib3.connectionpool][_new_conn #807] Starting new HTTPS connection (1): enterprisemessaging.ee.co.uk
2017/05/10 - 14:14:54 DEBUG {140507790042880} [urllib3.connectionpool][_make_request #401] "GET /cgphttp/servlet/sendmsg?username=XXXXXXXXXXXXXX&text=036104&destination=XXXXXXXXXXX&password=XXXXXXXX HTTP/1.1" 401 None
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][requests_request #317] HttpSMSProvider >><html>
<body>
An....
</body>

</html>
<<
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][_check_success #213] [_check_success] entering with config {u'URL': u'https://enterprisemessaging.ee.co.uk/cgphttp/servlet/sendmsg', u'SMS_PHONENUMBER_KEY': u'destination', u'SMS_TEXT_KEY': u'text', u'PARAMETER': {u'username': u'XXXXXXXXXX', u'password': u'XXXXXXXX'}, 'timeout': u'120'}
2017/05/10 - 14:14:54 DEBUG {140507790042880} [smsprovider.HttpSMSProvider][_check_success #214] [_check_success] entering with reply <html>
<body>
An error occurred.
</body>

</html>

2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.tokens.smstoken][sendSMS #891] [sendSMS] message submitted
2017/05/10 - 14:14:54 DEBUG {140507790042880} [linotp.lib.tokens.smstoken][sendSMS #891] [sendSMS] message submitted

**Comment by keyidentity-mirko** [comment]
Hi jfarcher,

could you please provide the working cmd-line request against your SMS Provider and the content of returned page.

Best Regards,

Mirko

**Comment by jfarcher** [comment]
Sure, here you go. variables are quite self explanatory.

 curl -X GET "http://enterprisemessaging.ee.co.uk/cgphttp/servlet/sendmsg?username=XXXXXXXXXXX&text=message&destination=XXXXXXXX&password=XXXXXXXXX"

**Comment by keyidentity-mirko** [comment]
Hi jfarcher,

thank you for the request. For debugging we require the return page from SMS Provider for a successful and a failed SMS submission.

Best Regards,

Mirko

**Comment by jfarcher** [comment]
I'm just waiting for them to get back to me with any logs,
a successful message sends the following:
0 001 OK
Message-ID: 786728932

Message-ID is different each time.

If I take a character out of the password and retry the CURL I get:
<html>
<body>
An error occurred.
</body>

</html>


Which is the same as I see in the logs when a failed send occurs. Same happens if i send a bad username.

If i remove a digit from the phone number I get
2 013 ERROR - destination value

I know its definitely the same username and password used in both LinOTP and the curl request as I can copy the string from the logfile.

**Comment by keyidentity-mirko** [comment]
Hi jfarcher,

so a "RETURN_SUCCESS":"OK" should work. For testing "RETURN_SUCCESS":".*" should work at least. But according to your log the authentication failed: "HTTP/1.1" 401 None"

Maybe try to extend you configuration with:

"HTTP_Method":"GET",

Best Regards,

Mirko

**Comment by jfarcher** [comment]
Hi,
I had already tried the "HTTP_Method":"GET" directive.
I tried setting the "RETURN_SUCCESS":".*" as you suggested and get the following in the log

2017/05/11 - 15:48:42 DEBUG {140507758040832} [linotp.lib.tokens.smstoken][sendSMS #886] [sendSMS] submitMessage: u'705062', to phone u'XXXXXXXXXX'
2017/05/11 - 15:48:42 DEBUG {140507758040832} [linotp.lib.tokens.smstoken][sendSMS #886] [sendSMS] submitMessage: u'705062', to phone u'XXXXXXXXXX'
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][_submitMessage #76] [submitMessage] submitting message 705062 to XXXXXXXXXX
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][_submitMessage #82] [submitMessage] by method GET
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][getParameters #188] [getParameters] urldata: {u'destination': u'XXXXXXXXXX'}
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][getParameters #193] [getParameters] urldata: {u'text': u'705062', u'destination': u'XXXXXXXXXX'}
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][getParameters #198] [getParameters] urldata: {u'username': u'XXXXXXXXXX', u'text': u'705062', u'password': u'XXXXXXXXXX', u'destination': u'XXXXXXXXXX'}
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][_submitMessage #85] [submitMessage] Now doing the Request
2017/05/11 - 15:48:42 INFO  {140507758040832} [urllib3.connectionpool][_new_conn #807] Starting new HTTPS connection (1): enterprisemessaging.ee.co.uk
2017/05/11 - 15:48:42 DEBUG {140507758040832} [urllib3.connectionpool][_make_request #401] "GET /cgphttp/servlet/sendmsg?username=XXXXXXXXXX&text=705062&destination=XXXXXXXXXX&password=XXXXXXXXXX HTTP/1.1" 401 None
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][requests_request #317] HttpSMSProvider >><html>
<body>
An....
</body>

</html>
<<
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][_check_success #213] [_check_success] entering with config {u'SMS_PHONENUMBER_KEY': u'destination', u'URL': u'https://enterprisemessaging.ee.co.uk/cgphttp/servlet/sendmsg', u'RETURN_SUCCESS': u'.*', u'HTTP_Method': u'GET', 'timeout': u'120', u'SMS_TEXT_KEY': u'text', u'PARAMETER': {u'username': u'XXXXXXXXXX', u'password': u'XXXXXXXXXX'}}
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][_check_success #214] [_check_success] entering with reply <html>
<body>
An error occurred.
</body>

</html>

2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][_check_success #240] [_check_success] success: .*
2017/05/11 - 15:48:42 WARNI {140507758040832} [smsprovider.HttpSMSProvider][_check_success #244] [_check_success] failed to send SMS. Reply does not match the RETURN_SUCCESS definition
2017/05/11 - 15:48:42 ERROR {140507758040832} [smsprovider.HttpSMSProvider][requests_request #321] HttpSMSProvider Exception('We received a none success reply from the SMS Gateway.',)
2017/05/11 - 15:48:42 WARNI {140507758040832} [smsprovider.HttpSMSProvider][_submitMessage #168] Failed to access the HTTP SMS Service with requests: Exception('Failed to send SMS. We received a none success reply from the SMS Gateway.',)
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][httplib_request #348] Do the request to https://enterprisemessaging.ee.co.uk/cgphttp/servlet/sendmsg with {u'username': u'XXXXXXXXXX', u'text': u'705062', u'password': u'XXXXXXXXXX', u'destination': u'XXXXXXXXXX'}
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][httplib_request #424] HttpSMSProvider >>0 001 OK
Message-ID...sage-ID: 787597333
<<
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][_check_success #213] [_check_success] entering with config {u'SMS_PHONENUMBER_KEY': u'destination', u'URL': u'https://enterprisemessaging.ee.co.uk/cgphttp/servlet/sendmsg', u'RETURN_SUCCESS': u'.*', u'HTTP_Method': u'GET', 'timeout': u'120', u'SMS_TEXT_KEY': u'text', u'PARAMETER': {u'username': u'XXXXXXXXXX', u'password': u'XXXXXXXXXX'}}
2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][_check_success #214] [_check_success] entering with reply 0 001 OK
Message-ID: 787597333

2017/05/11 - 15:48:42 DEBUG {140507758040832} [smsprovider.HttpSMSProvider][_check_success #240] [_check_success] success: .*
2017/05/11 - 15:48:42 WARNI {140507758040832} [smsprovider.HttpSMSProvider][_check_success #244] [_check_success] failed to send SMS. Reply does not match the RETURN_SUCCESS definition
2017/05/11 - 15:48:42 ERROR {140507758040832} [smsprovider.HttpSMSProvider][httplib_request #428] HttpSMSProvider Exception('We received a none success reply from the SMS Gateway.',)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/smsprovider/HttpSMSProvider.py", line 425, in httplib_request
    ret = self._check_success(reply)
  File "/usr/lib/pymodules/python2.7/smsprovider/HttpSMSProvider.py", line 246, in _check_success
    raise Exception("We received a none success reply from the "
Exception: We received a none success reply from the SMS Gateway.
2017/05/11 - 15:48:42 WARNI {140507758040832} [smsprovider.HttpSMSProvider][_submitMessage #176] Failed again to access the HTTP SMS Service: Exception('Failed to send SMS. We received a none success reply from the SMS Gateway.',)
2017/05/11 - 15:48:42 WARNI {140507758040832} [linotp.lib.tokens.smstoken][submitChallenge #478] [submitChallenge] The SMS could not be sent: Exception('Failed to send SMS. We received a none success reply from the SMS Gateway.',)
2017/05/11 - 15:48:42 WARNI {140507758040832} [linotp.lib.tokens.smstoken][submitChallenge #478] [submitChallenge] The SMS could not be sent: Exception('Failed to send SMS. We received a none success reply from the SMS Gateway.',)

It looks like it tries and fails a couple of times then succeeds. But the match is still not succeeding so I get a failed to send.

**Comment by keyidentity-mirko** [comment]
Hi again,

sorry, my mistake - of course "RETURN_SUCCESS_REGEX":".*" is required.

Best Regards,

Mirko

**Comment by jfarcher** [comment]
No worries, I've changed that and looking at the logs, the SMS fails to send this time, only the failures are present and I don't receive the text message.

**Comment by jfarcher** [comment]
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.tokens.smstoken][sendSMS #886] [sendSMS] submitMessage: u'403236', to phone u'XXXXXXXXXX'
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.tokens.smstoken][sendSMS #886] [sendSMS] submitMessage: u'403236', to phone u'XXXXXXXXXX'
2017/05/11 - 16:39:45 DEBUG {140507749648128} [smsprovider.HttpSMSProvider][_submitMessage #76] [submitMessage] submitting message 403236 to XXXXXXXXXX
2017/05/11 - 16:39:45 DEBUG {140507749648128} [smsprovider.HttpSMSProvider][_submitMessage #82] [submitMessage] by method GET
2017/05/11 - 16:39:45 DEBUG {140507749648128} [smsprovider.HttpSMSProvider][getParameters #188] [getParameters] urldata: {u'destination': u'XXXXXXXXXX'}
2017/05/11 - 16:39:45 DEBUG {140507749648128} [smsprovider.HttpSMSProvider][getParameters #193] [getParameters] urldata: {u'text': u'403236', u'destination': u'XXXXXXXXXX'}
2017/05/11 - 16:39:45 DEBUG {140507749648128} [smsprovider.HttpSMSProvider][getParameters #198] [getParameters] urldata: {u'username': u'XXXXXXXXXX', u'text': u'403236', u'password': u'XXXXXXXXXX', u'destination': u'XXXXXXXXXX'}
2017/05/11 - 16:39:45 DEBUG {140507749648128} [smsprovider.HttpSMSProvider][_submitMessage #85] [submitMessage] Now doing the Request
2017/05/11 - 16:39:45 INFO  {140507749648128} [urllib3.connectionpool][_new_conn #807] Starting new HTTPS connection (1): enterprisemessaging.ee.co.uk
2017/05/11 - 16:39:45 DEBUG {140507749648128} [urllib3.connectionpool][_make_request #401] "GET /cgphttp/servlet/sendmsg?username=XXXXXXXXXX&text=403236&destination=XXXXXXXXXX&password=XXXXXXXXXX HTTP/1.1" 401 None
2017/05/11 - 16:39:45 DEBUG {140507749648128} [smsprovider.HttpSMSProvider][requests_request #317] HttpSMSProvider >><html>
<body>
An....
</body>

</html>
<<
2017/05/11 - 16:39:45 DEBUG {140507749648128} [smsprovider.HttpSMSProvider][_check_success #213] [_check_success] entering with config {u'SMS_PHONENUMBER_KEY': u'destination', u'URL': u'https://enterprisemessaging.ee.co.uk/cgphttp/servlet/sendmsg', u'RETURN_SUCCESS_REGEX': u'.*', u'HTTP_Method': u'GET', 'timeout': u'120', u'SMS_TEXT_KEY': u'text', u'PARAMETER': {u'username': u'XXXXXXXXXX', u'password': u'XXXXXXXXXX'}}
2017/05/11 - 16:39:45 DEBUG {140507749648128} [smsprovider.HttpSMSProvider][_check_success #214] [_check_success] entering with reply <html>
<body>
An error occurred.
</body>

</html>

2017/05/11 - 16:39:45 DEBUG {140507749648128} [smsprovider.HttpSMSProvider][_check_success #219] [_check_success] sending SMS success
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.tokens.smstoken][sendSMS #891] [sendSMS] message submitted
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.tokens.smstoken][sendSMS #891] [sendSMS] message submitted
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.tokens.smstoken][setValidUntil #794] [setValidUntil] begin. set the due date
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.tokens.smstoken][setValidUntil #794] [setValidUntil] begin. set the due date
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.tokens.smstoken][loadLinOtpSMSValidTime #908] [loadLinOtpSMSValidTime] begin.
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.tokens.smstoken][loadLinOtpSMSValidTime #908] [loadLinOtpSMSValidTime] begin.
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.config][getFromConfig #1020] [getFromConfig] key:  SMSProviderTimeout
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.config][getFromConfig #1020] [getFromConfig] key:  SMSProviderTimeout
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]
2017/05/11 - 16:39:45 DEBUG {140507749648128} [linotp.lib.config][getLinotpConfig #138] [getLinotpConfig]

Is the logs.

**Comment by keyidentity-mirko** [comment]
Hi,

this seems like the the authentication against the SMSProvider does not work:

> 401 None

So probably best is to roll back to the configuration which sent SMS successfully from LinOTP and just adapt the "RETURN_SUCCESS_REGEX" parameter.

Best Regards,

Mirko

**Comment by jfarcher** [comment]
I only seem to get the 401 when a RETURN_SUCCESS_REGEX is specified. But without it I can't get a SUCCESS trigger.
I've not had a proper working configuration as yet with RETURN_SUCCESS or REGEX.

I'm still awaiting the logs from the vendor, hopefully they may shed some light on why we are seeing an auth failure.

**Comment by jfarcher** [comment]
Hi,
I've heard back from the SMS provider, all the requests that are hitting them are succeeding.

I don't think the HTTP command is succeeding when a REQUEST_SUCCESS_REGEX is specified.

**Comment by jfarcher** [comment]
Provider states that a request comes from 
python-requests/2.4.3 CPython/2.7.9 Linux/3.16.0-4-amd64 
and error 401 is received
This marries up with the logs.

**Comment by keyidentity-mirko** [comment]
Hi jfarcher,

I am not completely sure if I understand the current situation correctly. I try to sum up:

* the SMS are sent successful ("all the requests that are hitting them are succeeding")
* LinOTP receives a 401 and does not mark the challenge as valid

The RETURN_SUCCESS_REGEX should not change the actual request performed against the SMS Provider but is only for processing the received answer.

Unfortunately I do not find an evaluation proposal for the SMSProvider to reproduce the problem. Please contact me directly (mirko.ahnert@keyidentity.com) if you have a test account available for sharing.

Best Regards,

Mirko

**Comment by jfarcher** [comment]
Hi Mirko,
Sorry, SMS are not sending at all and I am getting a 401 from our messaging provider.
You can see the documented wget command from the provider here:
http://enterprisemessaging.ee.co.uk/Help/wget.htm

Initially it seemed that the adition of the RETURN_SUCCESS_REGEX was causing the sms send to fail, but I always get 401 with any configuration.

I'm not sure I will be able to get a test account but I will try. Otherwise, I'm happy to try things.

**Comment by keyidentity-mirko** [comment]
Hi,

due to jfarcher being so kind to provide us with a test account we have found the following SMSProvider configuration working for enterprisemessaging.ee.co.uk in LinOTP:

```
{ "URL":"https://enterprisemessaging.ee.co.uk/cgphttp/servlet/sendmsg?",
"SMS_TEXT_KEY":"text",
"SMS_PHONENUMBER_KEY":"destination",
"RETURN_SUCCESS_REGEX":"OK",
"USERNAME":"USERNAME",
"PASSWORD":"PW"
}
```

Have a good weekend!

Mirko
