### ISSUE TITLE
SMS auth failed

### ISSUE THREAD

**Issue by giacgbj** [LinOTP/LinOTP#61]
I call validate/simplecheck using the PIN and the SMS is sent, but:

```
2017/05/14 - 00:46:10 ERROR {140206248064768} [linotp.controllers.validate][simplecheck #703] [simplecheck] failed: TypeError("unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/linotp/controllers/validate.py", line 674, in simplecheck
    (ok, opt) = self._check(param)
  File "/usr/lib/python2.7/site-packages/linotp/controllers/validate.py", line 166, in _check
    (ok, opt) = vh.checkUserPass(user, passw, options=options)
  File "/usr/lib/python2.7/site-packages/linotp/lib/auth/validate.py", line 509, in checkUserPass
    tokenList, passw, user, options=options)
  File "/usr/lib/python2.7/site-packages/linotp/lib/auth/validate.py", line 699, in checkTokenList
    expired, _valid = Challenges.get_challenges(token)
  File "/usr/lib/python2.7/site-packages/linotp/lib/challenges.py", line 328, in get_challenges
    c_expire_time = c_start_time + datetime.timedelta(seconds=validity)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
2017/05/14 - 00:46:10 ERROR {140206248064768} [linotp.controllers.validate][simplecheck #703] [simplecheck] failed: TypeError("unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/linotp/controllers/validate.py", line 674, in simplecheck
    (ok, opt) = self._check(param)
  File "/usr/lib/python2.7/site-packages/linotp/controllers/validate.py", line 166, in _check
    (ok, opt) = vh.checkUserPass(user, passw, options=options)
  File "/usr/lib/python2.7/site-packages/linotp/lib/auth/validate.py", line 509, in checkUserPass
    tokenList, passw, user, options=options)
  File "/usr/lib/python2.7/site-packages/linotp/lib/auth/validate.py", line 699, in checkTokenList
    expired, _valid = Challenges.get_challenges(token)
  File "/usr/lib/python2.7/site-packages/linotp/lib/challenges.py", line 328, in get_challenges
    c_expire_time = c_start_time + datetime.timedelta(seconds=validity)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
```

When I call validate/simplecheck with PIN+OTP the response is ":-(" and the logs show:

```
2017/05/14 - 00:48:21 WARNI {140206323599104} [linotp.lib.auth.finishtokens][finish_checked_tokens #100] user u'someuser'@u'somerealm' failed to auth.
2017/05/14 - 00:48:21 WARNI {140206323599104} [linotp.lib.auth.finishtokens][finish_checked_tokens #100] user u'someuser'@u'somerealm' failed to auth.
```

During the steps the table CHALLENGES is always empty. I'm using LinOTP 2.9.1. This issue seems somehow related to #49 but I'm using an Oracle database.

**Comment by keyidentity-mirko** [comment]
Hi giacgbj,

thank you for the report. According to the source code the challenge data will be read from the database. From this data set the start time will be extracted. In you environment however the data set does not contain any data. Could you please check the permission settings on the tables? Is this an upgraded setup from a previous version of LinOTP? Did it work before? Could you please check if your challenge database table contains the column lchallenges and the column ptransid? If not the database migration during the update procedure might have failed. 

Best Regards,

Mirko

**Comment by giacgbj** [comment]
The database has never been migrated.
The colums PTRANSID and LCHALLENGE exist. Do you mean without the final "S" in "LCHALLENGE"?
We haven't modified the "standard" permissions of the database. Which permission should I check exactly and what do you expect?

**Comment by abinchy** [comment]
Hi Mirko,

I also have this issue where there is a high chance that the first authentication failed but always success the second attempt to validate the OTP. I realise that when I using the default SQLite in the linotp.ini, this issue is not happening. Is that an issue when using MYSQL database with LinOtp?

Besides, is there any documentation for the splitting data into multiple cells?

**Comment by dub357** [comment]
FYI - this is the same problem as https://github.com/LinOTP/LinOTP/issues/89
A fix has been posted there but it has not made it into the LinOTP codebase
