### ISSUE TITLE
SQL Resolver issue with id field of type integer

### ISSUE THREAD

**Issue by bastischubert** [LinOTP/LinOTP#69]
Hi,

the SelfService Portal stumbles upon the following error when trying to set a PIN for an otp, when the UserID Resolver uses SQLResolver and the id field is of type "integer".

``` 2017/10/12 - 12:44:39 ERROR {140483911587584} [linotp.controllers.userservice][setpin #924] Error setting OTP PIN: TypeError("object of type 'int' has no len()",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/linotp/controllers/userservice.py", line 891, in setpin
    if (True == th.isTokenOwner(serial, self.authUser)):
  File "/usr/lib/python2.7/site-packages/linotp/lib/token.py", line 485, in isTokenOwner
    if len(userid) + len(idResolver) + len(idResolverClass) == 0:
TypeError: object of type 'int' has no len()
2017/10/12 - 12:44:39 ERROR {140483911587584} [linotp.controllers.userservice][setpin #924] Error setting OTP PIN: TypeError("object of type 'int' has no len()",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/linotp/controllers/userservice.py", line 891, in setpin
    if (True == th.isTokenOwner(serial, self.authUser)):
  File "/usr/lib/python2.7/site-packages/linotp/lib/token.py", line 485, in isTokenOwner
    if len(userid) + len(idResolver) + len(idResolverClass) == 0:
TypeError: object of type 'int' has no len()
```

SQL Schema used:
```
CREATE TABLE `users` (
  `userid` mediumint(9) NOT NULL,
  `surname` varchar(255) NOT NULL,
  `givenname` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL DEFAULT '',
  `password` varchar(255) NOT NULL DEFAULT '',
  `email` varchar(255) NOT NULL DEFAULT '',
  `salt` varchar(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
maybe a cast to string on the userid could do the job?

**Comment by benammann** [comment]
+1
