### ISSUE TITLE
No Token Found!

### ISSUE THREAD

**Issue by videlanicolas** [LinOTP/LinOTP#71]
Hey, we are experiencing an error while trying to set a pin on a token. Without warning LinOTP sent "No Token Found!" message on the audit trail for a user that does have a token assigned. The traceback looks as following:

2017/xx/xx - 13:45:35 ERROR {13557f3e-0288-4813-96f3-716286707aec} [linotp.controllers.userservice][setpin #911] Error setting OTP PIN: TokenAdminError(description='no token found!', id=1102)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/linotp/controllers/userservice.py", line 878, in setpin
    if (True == th.isTokenOwner(serial, self.authUser)):
  File "/usr/lib/pymodules/python2.7/linotp/lib/token.py", line 484, in isTokenOwner
    raise TokenAdminError("no token found!", id=1102)
TokenAdminError: ERR1102: no token found!

We are looking to this error in the code and let you know if we find anything. Meanwhile I write down this issue so anyone can contribute for an answer.

Thanks!
Nicolás

**Comment by videlanicolas** [comment]
We've found that this message appears in LinOTP version 2.9.3.3, the way to reproduce the issue is to go beyond the attempts. Instead of logging a valid token but with no attempts left, it says "no token found". We are fixing this issue and making a pull request.
