### ISSUE TITLE
Linotp 2.9.3.4 - HSMException: ERR707: hsm not found!

### ISSUE THREAD

**Issue by jakobruessler** [LinOTP/LinOTP#83]
Hi there!
linotp-2.9.3.4 on a debian jessie. I enrolled a fresh HMAC-Token and got the following log messages while trying to log in for the first time:

2018/02/06 - 14:03:23 ERROR {140700370654976} [linotp.lib.auth.validate][checkTokenList #708] checking token <<class 'linotp.lib.tokens.hmactoken.HmacTokenClass'> {"'authenticated'": 'None', "'token'": '<<class \'linotp.model.Token\'> {"u\'LinOtpOtpLen\'": \'6L\', "u\'LinOtpCount\'": \'0L\', "u\'LinOtpKeyEnc\'": "u\'4f5ee7ac0747e90ec82cd33b96e61a4c27ef25fc79e70c2c100b7ed789447453f1412992a217a305b1363ac58acbb4db1a159bcffed5fa2833101ce7ce839eed9e7a1ccf4426b856c70d8acde49dd5bffe7d25a9c1683efd91e6f7003c5b6cadc2c3121a9ebc3563d71d58cfdd2e5648afa9cc8c3744d6a6d10545cbcc4e172666404d96816c576cd581b58278731826\'", "u\'LinOtpTokenType\'": "u\'HMAC\'", "u\'LinOtpIsactive\'": \'True\', "u\'LinOtpTokenId\'": \'55415L\', "u\'LinOtpPinHash\'": "u\'\'", "u\'LinOtpIdResolver\'": "u\'LDAPIdResolver.IdResolver.MBO-LDAP\'", "u\'LinOtpCountWindow\'": \'10L\', "\'realms\'": \'[<linotp.model.Realm object at 0x7ff724664dd0>]\', "u\'LinOtpTokenSerialnumber\'": "u\'LSGO22733944\'", "u\'LinOtpSyncWindow\'": \'1000L\', "u\'LinOtpMaxFail\'": \'10L\', "u\'LinOtpFailCount\'": \'1L\', "u\'LinOtpTokenDesc\'": "u\'Google Authenticator web prov\'", "u\'LinOtpTokenInfo\'": \'u\\\'{\\\\n"count_auth": 1, \\\\n"hashlib": "sha1"\\\\n}\\\'\', "u\'LinOtpTokenPinUser\'": "u\'\'", "u\'LinOtpTokenPinSO\'": "u\'\'", "u\'LinOtpUserid\'": "u\'1e79510e-43ac-1037-848b-c7be2909351a\'", "u\'LinOtpIdResClass\'": "u\'useridresolver.LDAPIdResolver.IdResolver.MBO-LDAP\'", "u\'LinOtpTokenPinSOIV\'": "u\'\'", "u\'LinOtpSeed\'": "u\'\'", "\'_sa_instance_state\'": \'<sqlalchemy.orm.state.InstanceState object at 0x7ff7248807d0>\', "u\'LinOtpTokenPinUserIV\'": "u\'\'", "u\'LinOtpKeyIV\'": "u\'90e67865ce3120e957c4907ec02f1612\'"}>', "'mode'": "['authenticate', 'challenge']", "'related_challenges'": '[]', "'valid_token'": '[]', "'challenge_token'": '[]', "'type'": "u'HMAC'", "'transId'": 'None', "'invalid_token'": '[]', "'auth_info'": "{'auth_info': [('pin_length', 0), ('otp_length', 6)]}", "'info'": '{}', "'matching_challenges'": '[]', "'hashlibStr'": "u'sha1'", "'pin_matching_token'": '[]', "'hKeyRequired'": 'True', "'supports_offline_mode'": 'False'}> failed: HSMException(description='hsm not found!', id=707)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/linotp/lib/auth/validate.py", line 704, in checkTokenList
    passw, user, options=check_options, challenges=challenges)
  File "/usr/lib/pymodules/python2.7/linotp/lib/tokenclass.py", line 693, in check_token
    options=options)
  File "/usr/lib/pymodules/python2.7/linotp/lib/tokenclass.py", line 816, in check_authenticate
    options=options)
  File "/usr/lib/pymodules/python2.7/linotp/lib/tokenclass.py", line 383, in authenticate
    pin_match = check_pin(self, pin, user=user, options=options)
  File "/usr/lib/pymodules/python2.7/linotp/lib/auth/validate.py", line 137, in check_pin
    res = token.checkPin(passw, options=options)
  File "/usr/lib/pymodules/python2.7/linotp/lib/tokenclass.py", line 1349, in checkPin
    iv, hashed_pin = SecretObj.hash_pin(pin or '', iv, hsm=hsm)
  File "/usr/lib/pymodules/python2.7/linotp/lib/crypto/__init__.py", line 207, in hash_pin
    iv = geturandom(16)
  File "/usr/lib/pymodules/python2.7/linotp/lib/crypto/__init__.py", line 761, in geturandom
    raise HSMException('hsm not found!')
HSMException: ERR707: hsm not found!

2018/02/06 - 14:03:23 ERROR {140700370654976} [linotp.controllers.validate][check #262] [check] validate/check failed: AttributeError("'DefaultSecurityModule' object has no attribute 'get'",)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/linotp/controllers/validate.py", line 233, in check
    (ok, opt) = self._check(param)
  File "/usr/lib/pymodules/python2.7/linotp/controllers/validate.py", line 161, in _check
    (ok, opt) = vh.checkUserPass(user, passw, options=options)
  File "/usr/lib/pymodules/python2.7/linotp/lib/auth/validate.py", line 518, in checkUserPass
    tokenList, passw, user, options=options)
  File "/usr/lib/pymodules/python2.7/linotp/lib/auth/validate.py", line 731, in checkTokenList
    Challenges.handle_related_challenge(matching_challenges)
  File "/usr/lib/pymodules/python2.7/linotp/lib/challenges.py", line 376, in handle_related_challenge
    hsm = context['hsm'].get('obj')
AttributeError: 'DefaultSecurityModule' object has no attribute 'get'

The second time and the following attempts all are successful (without changing anything). I saw those problems with all kind of different tokens. Any idea whats going on?

**Comment by synaccount** [comment]
Hello,
having issue with YubiKey.
version 2.10.5.3 
The passed Realm is not set, but the user name contains "@domain.com"

&realm=
(u'realm', u'')

`[Tue Mar 10 06:25:58.881187 2020]   mod_wsgi (pid=10971): Exception occurred processing WSGI script '/etc/linotp2/linotpapp.wsgi'.
[Tue Mar 10 06:25:58.881187 2020]   Traceback (most recent call last):
[Tue Mar 10 06:25:58.881187 2020]   File "/usr/lib/python2.7/dist-packages/paste/cascade.py", line 130, in __call__
[Tue Mar 10 06:25:58.893367 2020]     return self.apps[-1](environ, start_response)
[Tue Mar 10 06:25:58.893398 2020]   File "/usr/lib/python2.7/dist-packages/paste/registry.py", line 379, in __call__
[Tue Mar 10 06:25:58.895445 2020]     app_iter = self.application(environ, start_response)
[Tue Mar 10 06:25:58.895486 2020]   File "/usr/lib/python2.7/dist-packages/pylons/middleware.py", line 168, in __call__
[Tue Mar 10 06:25:58.897221 2020]     self.app, new_environ, catch_exc_info=True)
[Tue Mar 10 06:25:58.897254 2020]   File "/usr/lib/python2.7/dist-packages/pylons/util.py", line 50, in call_wsgi_application
[Tue Mar 10 06:25:58.898392 2020]     app_iter = application(environ, start_response)
[Tue Mar 10 06:25:58.898419 2020]   File "/usr/lib/python2.7/dist-packages/weberror/errormiddleware.py", line 165, in __call__
[Tue Mar 10 06:25:58.898448 2020]     return self.application(environ, start_response)
[Tue Mar 10 06:25:58.898463 2020]   File "/usr/lib/python2.7/dist-packages/beaker/middleware.py", line 73, in __call__
[Tue Mar 10 06:25:58.898486 2020]     return self.app(environ, start_response)
[Tue Mar 10 06:25:58.898500 2020]   File "/usr/lib/python2.7/dist-packages/beaker/middleware.py", line 156, in __call__
[Tue Mar 10 06:25:58.898522 2020]     return self.wrap_app(environ, session_start_response)
[Tue Mar 10 06:25:58.898536 2020]   File "/usr/lib/python2.7/dist-packages/routes/middleware.py", line 141, in __call__
[Tue Mar 10 06:25:58.898558 2020]     response = self.app(environ, start_response)
[Tue Mar 10 06:25:58.898571 2020]   File "/usr/lib/python2.7/dist-packages/pylons/wsgiapp.py", line 103, in __call__
[Tue Mar 10 06:25:58.898592 2020]     response = self.dispatch(controller, environ, start_response)
[Tue Mar 10 06:25:58.898605 2020]   File "/usr/lib/python2.7/dist-packages/pylons/wsgiapp.py", line 313, in dispatch
[Tue Mar 10 06:25:58.898625 2020]     return controller(environ, start_response)
[Tue Mar 10 06:25:58.898638 2020]   File "/usr/lib/python2.7/dist-packages/linotp/lib/base.py", line 567, in __call__
[Tue Mar 10 06:25:58.898661 2020]     self.create_context(request, environ)
[Tue Mar 10 06:25:58.898675 2020]   File "/usr/lib/python2.7/dist-packages/linotp/lib/base.py", line 735, in create_context
[Tue Mar 10 06:25:58.898696 2020]     requestUser = getUserFromParam(self.request_params)
[Tue Mar 10 06:25:58.898733 2020]   File "/usr/lib/python2.7/dist-packages/linotp/lib/user.py", line 556, in getUserFromParam
[Tue Mar 10 06:25:58.898757 2020]     res = getResolversOfUser(usr)
[Tue Mar 10 06:25:58.898785 2020]   File "/usr/lib/python2.7/dist-packages/linotp/lib/user.py", line 897, in getResolversOfUser
[Tue Mar 10 06:25:58.898808 2020]     resolvers = get_resolvers_of_user(login, realm)
[Tue Mar 10 06:25:58.898823 2020]   File "/usr/lib/python2.7/dist-packages/linotp/lib/user.py", line 1028, in get_resolvers_of_user
[Tue Mar 10 06:25:58.898840 2020]     raise exx
[Tue Mar 10 06:25:58.898860 2020] AttributeError: 'DefaultSecurityModule' object has no attribute 'get'
`
