### ISSUE TITLE
Can't reconnect until invalid transaction is rolled back

### ISSUE THREAD

**Issue by PleaseTakeItEasy** [LinOTP/LinOTP#87]
I am on LinOTP 2.10.0.3 and every once in a while I am getting errors such as the one below
[Mon Apr 02 16:10:30.474748 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]
[Mon Apr 02 16:10:30.474751 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]
[Mon Apr 02 16:10:30.474755 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078] CGI Variables
[Mon Apr 02 16:10:30.474758 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078] -------------
[Mon Apr 02 16:10:30.474762 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   CONTEXT_DOCUMENT_ROOT: '/var/www/html'
[Mon Apr 02 16:10:30.474765 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   DOCUMENT_ROOT: '/var/www/html'
[Mon Apr 02 16:10:30.474769 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   GATEWAY_INTERFACE: 'CGI/1.1'
[Mon Apr 02 16:10:30.474773 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
[Mon Apr 02 16:10:30.474776 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   HTTP_ACCEPT_ENCODING: 'gzip, deflate, br'
[Mon Apr 02 16:10:30.474780 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   HTTP_ACCEPT_LANGUAGE: 'en-US,en;q=0.9'
[Mon Apr 02 16:10:30.474784 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   HTTP_CONNECTION: 'keep-alive'
[Mon Apr 02 16:10:30.474787 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   HTTP_HOST: ''
[Mon Apr 02 16:10:30.474794 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   HTTP_UPGRADE_INSECURE_REQUESTS: '1'
[Mon Apr 02 16:10:30.474798 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   HTTP_USER_AGENT: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'
[Mon Apr 02 16:10:30.474803 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   PATH_INFO: '/selfservice/'
[Mon Apr 02 16:10:30.474807 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   PATH_TRANSLATED: '/etc/linotp2/linotpapp.wsgi/selfservice/'
[Mon Apr 02 16:10:30.474810 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   REMOTE_ADDR: ''
[Mon Apr 02 16:10:30.474814 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   REMOTE_PORT: '18504'
[Mon Apr 02 16:10:30.474817 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   REQUEST_METHOD: 'GET'
[Mon Apr 02 16:10:30.474821 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   REQUEST_SCHEME: 'https'
[Mon Apr 02 16:10:30.474824 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   REQUEST_URI: '/selfservice/'
[Mon Apr 02 16:10:30.474828 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   SCRIPT_FILENAME: '/etc/linotp2/linotpapp.wsgi'
[Mon Apr 02 16:10:30.474831 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   SERVER_ADDR: ''
[Mon Apr 02 16:10:30.474835 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   SERVER_ADMIN: 'webmaster@localhost'
[Mon Apr 02 16:10:30.474838 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   SERVER_NAME: ''
[Mon Apr 02 16:10:30.474841 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   SERVER_PORT: '443'
[Mon Apr 02 16:10:30.474845 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   SERVER_PROTOCOL: 'HTTP/1.1'
[Mon Apr 02 16:10:30.474848 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   SERVER_SIGNATURE: '<address></address>\\n'
[Mon Apr 02 16:10:30.474852 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   SERVER_SOFTWARE: ''
[Mon Apr 02 16:10:30.474856 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]
[Mon Apr 02 16:10:30.474859 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]
[Mon Apr 02 16:10:30.474862 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078] WSGI Variables
[Mon Apr 02 16:10:30.474866 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078] --------------
[Mon Apr 02 16:10:30.474869 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   
[Mon Apr 02 16:10:30.474873 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   application: <beaker.middleware.CacheMiddleware object at 0x7f6d5b1d2cd0>
[Mon Apr 02 16:10:30.474877 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   beaker.cache: <beaker.cache.CacheManager object at 0x7f6d5b1d28d0>
[Mon Apr 02 16:10:30.474880 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   beaker.get_session: <bound method SessionMiddleware._get_session of <beaker.middleware.SessionMiddleware object at 0x7f6d5b1d23d0>>
[Mon Apr 02 16:10:30.474884 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   beaker.session: {'_id': 'ddff27e75b334d78a16ae9a622d75d8b'}
[Mon Apr 02 16:10:30.474888 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.application_group: '|'
[Mon Apr 02 16:10:30.474892 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.callable_object: 'application'
[Mon Apr 02 16:10:30.474898 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.daemon_connects: '1'
[Mon Apr 02 16:10:30.474902 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.daemon_restarts: '0'
[Mon Apr 02 16:10:30.474906 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.daemon_start: '1522699830444366'
[Mon Apr 02 16:10:30.474910 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.enable_sendfile: '0'
[Mon Apr 02 16:10:30.474913 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.handler_script: ''
[Mon Apr 02 16:10:30.474917 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.input_chunked: '0'
[Mon Apr 02 16:10:30.474920 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.listener_host: ''
[Mon Apr 02 16:10:30.474924 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.listener_port: '443'
[Mon Apr 02 16:10:30.474927 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.process_group: 'linotp'
[Mon Apr 02 16:10:30.474931 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.queue_start: '1522699830444228'
[Mon Apr 02 16:10:30.474934 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.request_handler: 'wsgi-script'
[Mon Apr 02 16:10:30.474938 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.request_start: '1522699830444097'
[Mon Apr 02 16:10:30.474941 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.script_reloading: '1'
[Mon Apr 02 16:10:30.474947 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.script_start: '1522699830444387'
[Mon Apr 02 16:10:30.474953 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   mod_wsgi.version: (4, 3, 0)
[Mon Apr 02 16:10:30.474959 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   paste.registry: <paste.registry.Registry object at 0x7f6d5b0d3dd0>
[Mon Apr 02 16:10:30.474966 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   paste.throw_errors: True
[Mon Apr 02 16:10:30.474972 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   pylons.environ_config: {'session': 'beaker.session', 'cache': 'beaker.cache'}
[Mon Apr 02 16:10:30.474979 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   pylons.log_debug: True
[Mon Apr 02 16:10:30.474985 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   pylons.pylons: <pylons.util.PylonsContext object at 0x7f6d5b00e090>
[Mon Apr 02 16:10:30.474989 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   pylons.routes_dict: {'action': u'index', 'controller': u'selfservice'}
[Mon Apr 02 16:10:30.474993 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   routes.route: <routes.route.Route object at 0x7f6d5b9e5ed0>
[Mon Apr 02 16:10:30.474997 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   routes.url: <routes.util.URLGenerator object at 0x7f6d5b006d50>
[Mon Apr 02 16:10:30.475001 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   wsgi process: 'Multi process AND threads (?)'
[Mon Apr 02 16:10:30.475004 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   wsgi.file_wrapper: <type 'mod_wsgi.FileWrapper'>
[Mon Apr 02 16:10:30.475008 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   wsgiorg.routing_args: (<routes.util.URLGenerator object at 0x7f6d5b006d50>, {'action': u'index', 'controller': u'selfservice'})
[Mon Apr 02 16:10:30.475012 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078] ------------------------------------------------------------
[Mon Apr 02 16:10:30.479267 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078] mod_wsgi (pid=4942): Exception occurred processing WSGI script '/etc/linotp2/linotpapp.wsgi'.
[Mon Apr 02 16:10:30.479375 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078] Traceback (most recent call last):
[Mon Apr 02 16:10:30.479405 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/paste/cascade.py", line 130, in __call__
[Mon Apr 02 16:10:30.479513 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     return self.apps[-1](environ, start_response)
[Mon Apr 02 16:10:30.479530 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/paste/registry.py", line 379, in __call__
[Mon Apr 02 16:10:30.481839 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     app_iter = self.application(environ, start_response)
[Mon Apr 02 16:10:30.481860 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/pylons/middleware.py", line 168, in __call__
[Mon Apr 02 16:10:30.482682 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     self.app, new_environ, catch_exc_info=True)
[Mon Apr 02 16:10:30.482700 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/pylons/util.py", line 50, in call_wsgi_application
[Mon Apr 02 16:10:30.483923 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     app_iter = application(environ, start_response)
[Mon Apr 02 16:10:30.483942 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/weberror/errormiddleware.py", line 156, in __call__
[Mon Apr 02 16:10:30.483968 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     return self.application(environ, start_response)
[Mon Apr 02 16:10:30.483980 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/beaker/middleware.py", line 73, in __call__
[Mon Apr 02 16:10:30.484000 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     return self.app(environ, start_response)
[Mon Apr 02 16:10:30.484011 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/beaker/middleware.py", line 155, in __call__
[Mon Apr 02 16:10:30.484030 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     return self.wrap_app(environ, session_start_response)
[Mon Apr 02 16:10:30.484041 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/routes/middleware.py", line 136, in __call__
[Mon Apr 02 16:10:30.484059 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     response = self.app(environ, start_response)
[Mon Apr 02 16:10:30.484071 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/pylons/wsgiapp.py", line 103, in __call__
[Mon Apr 02 16:10:30.484088 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     response = self.dispatch(controller, environ, start_response)
[Mon Apr 02 16:10:30.484100 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/pylons/wsgiapp.py", line 304, in dispatch
[Mon Apr 02 16:10:30.484117 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     controller = controller()
[Mon Apr 02 16:10:30.484128 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/linotp/lib/base.py", line 477, in __init__
[Mon Apr 02 16:10:30.484147 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     l_config = getLinotpConfig()
[Mon Apr 02 16:10:30.484157 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/linotp/lib/config/__init__.py", line 110, in getLinotpConfig
[Mon Apr 02 16:10:30.484184 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     ret = LinOtpConfig()
[Mon Apr 02 16:10:30.484196 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/linotp/lib/config/config_class.py", line 99, in __init__
[Mon Apr 02 16:10:30.484214 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     db_conf_date = _retrieveConfigDB('linotp.Config')
[Mon Apr 02 16:10:30.484225 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/linotp/lib/config/db_api.py", line 303, in _retrieveConfigDB
[Mon Apr 02 16:10:30.484244 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     entries = Session.query(Config).filter(Config.Key == key).all()
[Mon Apr 02 16:10:30.484255 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2588, in all
[Mon Apr 02 16:10:30.484274 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     return list(self)
[Mon Apr 02 16:10:30.484285 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
[Mon Apr 02 16:10:30.484302 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     return self._execute_and_instances(context)
[Mon Apr 02 16:10:30.484314 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
[Mon Apr 02 16:10:30.484331 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     result = conn.execute(querycontext.statement, self._params)
[Mon Apr 02 16:10:30.484342 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
[Mon Apr 02 16:10:30.484361 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     return meth(self, multiparams, params)
[Mon Apr 02 16:10:30.484373 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
[Mon Apr 02 16:10:30.484391 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     return connection._execute_clauseelement(self, multiparams, params)
[Mon Apr 02 16:10:30.484402 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
[Mon Apr 02 16:10:30.484420 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     compiled_sql, distilled_params
[Mon Apr 02 16:10:30.484431 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
[Mon Apr 02 16:10:30.484448 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     None, None)
[Mon Apr 02 16:10:30.484458 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
[Mon Apr 02 16:10:30.484475 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     exc_info
[Mon Apr 02 16:10:30.484486 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
[Mon Apr 02 16:10:30.484503 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     reraise(type(exception), exception, tb=exc_tb)
[Mon Apr 02 16:10:30.484513 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
[Mon Apr 02 16:10:30.484537 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     conn = self._revalidate_connection()
[Mon Apr 02 16:10:30.484549 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
[Mon Apr 02 16:10:30.484566 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078]     "Can't reconnect until invalid "
[Mon Apr 02 16:10:30.484631 2018] [wsgi:error] [pid 4942:tid 140108017178368] [remote 10.1.15.2:9078] StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'SELECT `Config`.`Key` AS `Config_Key`, `Config`.`Value` AS `Config_Value`, `Config`.`Type` AS `Config_Type`, `Config`.`Description` AS `Config_Description` \\nFROM `Config` \\nWHERE `Config`.`Key` = %(Key_1)s'] [parameters: [immutabledict({})]]

**Comment by aneutron** [comment]
Hello, I believe I have the same exact issue. Did you happen to find out what caused this issue ?

**Comment by aneutron** [comment]
Hey @megfault, any idea what this could be please ?

**Comment by vampy101** [comment]
We're starting to see this as well on our LinOTP environment.  Generally a restart of Apache seems to allow it work again, but I'm not sure if that's the best way to resolve the issue.
